import { hex } from './png.mjs';

/** Shared colours, taken from the character sheet and concept mock-up. */
export const C = {
  outline: hex('#1a1a2e'),
  skin: hex('#f4a261'),
  skinShade: hex('#d98c4a'),
  hair: hex('#7a3f1d'),
  hairLight: hex('#a8602c'),
  shirt: hex('#2a9d8f'),
  shirtLight: hex('#4fc1a6'),
  shorts: hex('#1e2a44'),
  shortsLight: hex('#3a4a6b'),
  boardYellow: hex('#ffc43d'),
  boardOrange: hex('#f4862f'),
  boardRed: hex('#e63946'),
  boardDark: hex('#2b2d42'),
  white: hex('#f8fbff'),
  foam: hex('#dff3ff'),
  waterLight: hex('#5fb3f0'),
  water: hex('#2a66c4'),
  waterDeep: hex('#1e4fa3'),
  waterDark: hex('#173f85'),
  rock: hex('#6b4f3a'),
  rockLight: hex('#9a7b5a'),
  rockDark: hex('#3e2d21'),
  shark: hex('#4a5068'),
  sharkDark: hex('#2b3042'),
  sharkBelly: hex('#9aa3b8'),
  red: hex('#ff3b3b'),
  skyTop: hex('#f26b4e'),
  skyMid: hex('#f7a04b'),
  skyLow: hex('#ffcf6b'),
  sun: hex('#ffe9a0'),
  sunCore: hex('#fff6cf'),
  island: hex('#4a3b2c'),
  islandLight: hex('#6a5540'),
  cloud: hex('#ffe4b8'),
  cyan: hex('#7ff6ff'),
  yellow: hex('#ffd166'),
};

/** Character legend used by the ASCII sprite maps. */
export const LEGEND = {
  k: C.outline,
  s: C.skin,
  S: C.skinShade,
  h: C.hair,
  H: C.hairLight,
  t: C.shirt,
  T: C.shirtLight,
  n: C.shorts,
  N: C.shortsLight,
  y: C.boardYellow,
  o: C.boardOrange,
  r: C.boardRed,
  b: C.boardDark,
  w: C.white,
  f: C.foam,
  l: C.waterLight,
  a: C.water,
  d: C.waterDeep,
  D: C.waterDark,
  R: C.rock,
  L: C.rockLight,
  K: C.rockDark,
  g: C.shark,
  G: C.sharkDark,
  B: C.sharkBelly,
  x: C.red,
  X: hex('#ff7b7b'),
  c: C.cyan,
};
